export const cellsArray = [
    {
        id: 1,
        nome_celula: 'Célula 1',
        secretarioId: 1,
        secretario: 'Fernando Silva',
        membros: [
            {
                nome: 'João Silva',
                telefone: '123456789',
                sexo: 'Masculino',
                data_nascimento: '1990-05-20',
                cristao: true,
                novo_convertido: false,
                escola_de_lideres: false,
                descubra: false,
            },
            {
                nome: 'Maria Santos',
                telefone: '987654321',
                sexo: 'Feminino',
                data_nascimento: '1985-08-15',
                cristao: true,
                novo_convertido: true,
                escola_de_lideres: true,
                descubra: false,
            },
            {
                nome: 'Pedro Oliveira',
                telefone: '555555555',
                sexo: 'Masculino',
                data_nascimento: '1978-03-10',
                cristao: true,
                novo_convertido: false,
                escola_de_lideres: false,
                descubra: true,
            },
            {
                nome: 'Ana Costa',
                telefone: '111111111',
                sexo: 'Feminino',
                data_nascimento: '2000-11-30',
                cristao: true,
                novo_convertido: true,
                escola_de_lideres: true,
                descubra: true,
            },
            {
                nome: 'Lucas Pereira',
                telefone: '999999999',
                sexo: 'Masculino',
                data_nascimento: '1995-07-25',
                cristao: true,
                novo_convertido: false,
                escola_de_lideres: true,
                descubra: true,
            },
        ],
        larAnfitriaoId: 1,
    },
    {
        id: 2,
        nome_celula: 'Célula 2',
        secretario: 'Carolina Oliveira',
        secretarioId: 2,
        membros: [
            {
                nome: 'Carla Rodrigues',
                telefone: '777777777',
                sexo: 'Feminino',
                data_nascimento: '1983-02-18',
                cristao: true,
                novo_convertido: true,
                escola_de_lideres: false,
                descubra: false,
            },
            {
                nome: 'Mateus Silva',
                telefone: '888888888',
                sexo: 'Masculino',
                data_nascimento: '1970-12-05',
                cristao: true,
                novo_convertido: false,
                escola_de_lideres: true,
                descubra: false,
            },
            {
                nome: 'Julia Pereira',
                telefone: '666666666',
                sexo: 'Feminino',
                data_nascimento: '1998-09-12',
                cristao: true,
                novo_convertido: true,
                escola_de_lideres: true,
                descubra: true,
            },
            {
                nome: 'Carlos Santos',
                telefone: '444444444',
                sexo: 'Masculino',
                data_nascimento: '1987-04-03',
                cristao: true,
                novo_convertido: false,
                escola_de_lideres: false,
                descubra: true,
            },
            {
                nome: 'Amanda Costa',
                telefone: '222222222',
                sexo: 'Feminino',
                data_nascimento: '1993-06-28',
                cristao: true,
                novo_convertido: true,
                escola_de_lideres: false,
                descubra: true,
            },
        ],
        larAnfitriaoId: 2,
    },
    {
        id: 3,
        nome_celula: 'Célula 3',
        secretarioId: 3,
        secretario: 'Rafaela Santos',
        membros: [
            {
                nome: 'Renato Oliveira',
                telefone: '555111222',
                sexo: 'Masculino',
                data_nascimento: '1976-10-08',
                cristao: true,
                novo_convertido: false,
                escola_de_lideres: false,
                descubra: false,
            },
            {
                nome: 'Fernanda Rodrigues',
                telefone: '999333444',
                sexo: 'Feminino',
                data_nascimento: '1989-01-25',
                cristao: true,
                novo_convertido: true,
                escola_de_lideres: true,
                descubra: false,
            },
            {
                nome: 'Roberto Santos',
                telefone: '777444666',
                sexo: 'Masculino',
                data_nascimento: '1982-06-15',
                cristao: true,
                novo_convertido: false,
                escola_de_lideres: true,
                descubra: true,
            },
            {
                nome: 'Camila Silva',
                telefone: '111222333',
                sexo: 'Feminino',
                data_nascimento: '1997-03-30',
                cristao: true,
                novo_convertido: true,
                escola_de_lideres: false,
                descubra: true,
            },
            {
                nome: 'Ricardo Costa',
                telefone: '888999000',
                sexo: 'Masculino',
                data_nascimento: '2002-09-20',
                cristao: true,
                novo_convertido: false,
                escola_de_lideres: true,
                descubra: true,
            },
        ],
        larAnfitriaoId: 3,
    },
    {
        id: 4,
        nome_celula: 'Célula 4',
        secretarioId: 4,
        secretario: 'Leonardo Costa',
        membros: [
            {
                nome: 'Sandra Santos',
                telefone: '555888999',
                sexo: 'Feminino',
                data_nascimento: '1995-11-12',
                cristao: true,
                novo_convertido: false,
                escola_de_lideres: false,
                descubra: false,
            },
            {
                nome: 'Daniel Oliveira',
                telefone: '777222333',
                sexo: 'Masculino',
                data_nascimento: '1990-04-27',
                cristao: true,
                novo_convertido: true,
                escola_de_lideres: true,
                descubra: false,
            },
            {
                nome: 'Leticia Silva',
                telefone: '333666999',
                sexo: 'Feminino',
                data_nascimento: '1978-08-22',
                cristao: true,
                novo_convertido: true,
                escola_de_lideres: true,
                descubra: true,
            },
            {
                nome: 'Rodrigo Costa',
                telefone: '111444777',
                sexo: 'Masculino',
                data_nascimento: '2001-02-15',
                cristao: true,
                novo_convertido: false,
                escola_de_lideres: false,
                descubra: true,
            },
            {
                nome: 'Patricia Rodrigues',
                telefone: '888111222',
                sexo: 'Feminino',
                data_nascimento: '1986-07-05',
                cristao: true,
                novo_convertido: true,
                escola_de_lideres: false,
                descubra: true,
            },
        ],
        larAnfitriaoId: 4,
    },
] as const;
